AvitalTamir/cyphernetes

- README.md
- ROADMAP.md
- cmd/cyphernetes.go
- cmd/k8s_query.go
- cmd/lexer.go
- cmd/parser.go
- cmd/parser_test.go
- grammar/cyphernetes.y
This PR adds support for relationship tokens ( `-[r:Relationship {prop: "value", ...}]->` ).
It also refactors NodePatterns and MatchClauses for reusability.
> Add relationship tokens

- README.md
- ROADMAP.md
- cmd/k8s_client.go
- cmd/k8s_query.go
- cmd/relationships.go
First working relationship rule defined: pods -> rs
This is based on a generic rule system that should now be enhanced with more relationship rules.
> This PR introduces the Kubernetes graph

- README.md
- ROADMAP.md
- grammar/cyphernetes.y
- pkg/parser/cyphernetes.go
- pkg/parser/k8s_query.go
- pkg/parser/lexer.go
- pkg/parser/lexer_test.go
- pkg/parser/parser.go
- pkg/parser/parser_test.go
Add support for `SET` clauses, allowing the user to update Kubernetes resources with Cyphernetes.
> Add SET clause

- .gitignore
- cmd/cyphernetes/shell.go
- pkg/parser/k8s_query.go
- pkg/parser/parser.go
* Feature: cache clearing and printing functions
* Feature: print query execution time in shell
* Feature: function to clear/print cache, enable debug logs and query execution time toggles in shell
* Bugfix: issue with progagated errors printed multiple times
* Bugfix: Matches with both field and label selectors handeled wrong depending on property order
> Shell improvements

- pkg/parser/k8s_query.go
Fix a bug in where clause filtering where the result array would contain wrong results
> (bugfix) where clause filtering

- README.md
- USAGE.md
- cmd/cyphernetes/shell-graph.go
- cmd/cyphernetes/shell.go
- go.mod
- go.sum
* Remove Graphviz dependency
* Graphs disabled and have LR layout by default
* Add graph layout toggle
* Update docs
> Remove graphviz

- pkg/parser/relationship_types.go
This PR also fixes bad code style repeated across some of the predefined relationships.
> fix(parser): service to endpoint relationship

- go.mod
- go.sum
- operator/go.mod
- operator/go.sum
- operator/internal/controller/dynamicoperator_controller.go
- pkg/parser/k8s_query.go
- pkg/parser/k8s_query_test.go
- pkg/parser/lexer.go
- pkg/parser/relationship.go
This PR also fixes escaped dots in SET clause paths
> fix: support escaping in extrafilters and set clause

- pkg/parser/k8s_query.go
> Fix return output for nested items

- cmd/cyphernetes/main_test.go
- cmd/cyphernetes/query.go
- cmd/cyphernetes/root.go
- cmd/cyphernetes/shell.go
- cmd/cyphernetes/shell_test.go
- pkg/parser/parser.go
> feat(shell): support no color mode

- pkg/core/k8s_query.go
this race condition happens during relationship processing
> fix(client): lock access to resultmap when accessing via goroutine

- pkg/core/k8s_query.go
- pkg/core/relationship.go
- pkg/provider/apiserver/provider.go
> fix: ambiguity in core group

- cmd/cyphernetes/query.go
- cmd/cyphernetes/root.go
- cmd/cyphernetes/shell.go
Also: move the `--format` flag to shell/query only
> fix: skip init outside of shell context

- pkg/core/e2e/e2e_test.go
- pkg/core/k8s_query.go
- pkg/core/lexer.go
- pkg/core/parser_test.go
- pkg/provider/apiserver/provider.go
> use strategic merge patches in SET operations

- cmd/cyphernetes/main_test.go
- cmd/cyphernetes/query.go
- operator/internal/controller/dynamicoperator_controller.go
- pkg/core/k8s_query.go
- pkg/core/relationship.go
- pkg/provider/apiserver/provider.go
> add quiet mode to suppress progress bars+messages in query command

- docs/docusaurus.config.ts
- docs/src/css/custom.css
> docs: add PRoduct Hunt announcement

- cmd/cyphernetes/query.go
> bug(query): skip ANSI colors when no interactive terminal attached

- docs/docs/examples.md
Some updates and corrections to the examples page
> chore(docs): update examples

- cmd/cyphernetes/shell.go
- cmd/cyphernetes/shell_test.go
- go.mod
- go.sum
- operator/go.mod
- operator/go.sum
- pkg/core/utils.go
Added shell directives `\rr` to fetch the configured relationship list and `\rl` to describe a single relationship.
> feat: :sparkles: Added shell directive to fetch and describe relationships

- cmd/cyphernetes/api.go
- cmd/cyphernetes/graph.go
- cmd/cyphernetes/graph_test.go
- cmd/cyphernetes/macro.go
- cmd/cyphernetes/shell.go
> fix: sanitize graph in web

- docs/docusaurus.config.ts
> docs(footer): add LinkedIn

- pkg/core/execute.go
- pkg/core/relationship.go
Reverts AvitalTamir/cyphernetes#254
> Revert "Fix for setting namespace after execute query"

- pkg/core/kind_resolution_test.go
- pkg/core/relationship_types.go
> fix: add pod->pvc and pvc->pv relationships
