- pkg/parser/k8s_query.go
- pkg/parser/relationships.go
3 major changes:
* The JSON output generated by return clauses was previously broken, it would create a structure like this:
```json
"d": {
"metadata": {
"name": [
"foo",
"bar",
]
}
}
```
instead of this:
```json
"d": [
{
"metadata": {
"name": "foo"
}
},
{
"metadata": {
"name": "bar"
}
}  
]
```
This PR fixes this issue
* Relationships are now correctly filtered on both ends, meaning resources are filtered to match the relationship pattern no matter which side of the edge they're on
* Moved the extraFilters function to the `getNodeResources` function so that filtering happens pre-applying relationship rules
> Improved JSON output

- cmd/cyphernetes/shell.go
- pkg/parser/k8s_query.go
- pkg/parser/relationships.go
* Correctly return full resource when returning node name
* Move query exec time print to end of results in return statements
* Fixed `hasLabels` label matching function (changed to general `containsAll`)
> Qol improvements

- Makefile
right now the binary name seems a bit off for `go build`, thus removing the `arch` and `os` suffix info.
relates to https://github.com/Homebrew/homebrew-core/pull/188365
> chore: make the binary generic

- .github/workflows/pr-checks.yml
- cmd/cyphernetes/shell.go
- operator/go.mod
- operator/go.sum
- pkg/parser/k8s_client.go
Make sure we're respecting $KUBECONFIG, rest config, recommended home file and all regular config loading rules.
This PR also fixes a bug: Exit with error instead of panic when failing to load config
Additionally, there's a small fix here to the operator tests which didn't run successfully but still passed previously.
> fix(k8s-client): use full client config loading rules

- .vscode/launch.json
- cmd/cyphernetes/query.go
- cmd/cyphernetes/root.go
- cmd/cyphernetes/shell-autocomplete.go
- cmd/cyphernetes/shell.go
- pkg/parser/k8s_client.go
- pkg/parser/parser.go
- pkg/parser/relationship.go
- pkg/parser/relationship_types.go
After scanning the openAPI document, we can now infer many relationships automatically from field names ending with either `Name`, `Ref`, or `KeyRef`.
The PR removes such relationships that were hardcoded before, as well as several broken hardcoded relationships.
We now also discover relationships by references while traversing the cluster's openapi document.
> feat: discover relationships by property name

- docs/LANGUAGE.md
Fixes #115 
Changes made in this PR:
1. fix minor typos outlined from #115
> [ISSUE-115] fix typos in `docs/LANGUAGE.md`

- USAGE.md
- docs/LANGUAGE.md
- pkg/parser/k8s_query.go
- pkg/parser/k8s_query_test.go
Resolves #102 
Changes made in this PR:
1. Implement logic for adding support SUM on CPU and Memory resources
2. Implement helper functions such as `convertToMilliCPU()`, `convertMilliCPUToStandard`, `convertMemoryToBytes`, `convertBytesToMemory` for handling string and int manipulation for summing K8 CPU and Memory values ( which needs unit conversion ).
3. add unit tests
4. add SUM cpu and memory query example in docs
Notes:
1. Manually tested with `cyphernetes shell -A`, trying these commands:
```
MATCH (p:Pod) RETURN SUM{p.spec.containers[0].resources.limits.cpu};
MATCH (p:Pod) RETURN SUM{p.spec.containers[0].resources.requests.cpu};
MATCH (p:Pod) RETURN SUM{p.spec.containers[0].resources.limits.memory};
MATCH (p:Pod) RETURN SUM{p.spec.containers[0].resources.requests.memory};
MATCH …
```
> [ISSUE-102] Add support SUM on CPU and Memory

- cmd/cyphernetes/main_test.go
- pkg/parser/k8s_client.go
- pkg/parser/k8s_query.go
- pkg/parser/parser.go
Resolves  #111 
Changes made in this PR:
1. In `logDebug()`, prepend "[DEBUG] "
2. Implement `logError()` and prepend "[ERROR] "
3. Convert the commented out `fmt.` statements into appropriate debug or error level logs
4. Add test `TestCyphernetesShellWithLogLevelFlag` and `TestCyphernetesShellWithLogLevelFlagHelper`
Notes:
1. `log.Println()` outputs to `Stderr` by default hence checking `stderr` for the added test
> [ISSUE-111] Implement and patch log levels for `debug` and `error`

- README.md
- cmd/cyphernetes/shell-autocomplete.go
- cmd/cyphernetes/shell.go
- docs/LANGUAGE.md
- grammar/cyphernetes.y
- pkg/parser/cyphernetes.go
- pkg/parser/k8s_client.go
- pkg/parser/k8s_query.go
- pkg/parser/lexer.go
- pkg/parser/lexer_test.go
- pkg/parser/parser.go
- pkg/parser/parser_test.go
This PR adds support for multi-cluster queries using the `IN` keyword:
```graphql
IN staging, production
MATCH (d:Deployment {namespace: "kube-system"})
RETURN d.metadata.name
```
Cyphernetes will run the query for each context in the `IN` clause, and return the results in a single payload.
The results will be prefixed with the context name, followed by an underscore:
```json
{
"staging_d": [
{
"metadata": {
"name": "coredns"
}
}
],
"production_d": [
{
"metadata": {
"name": "coredns"
}
}
}
```
> Add multi cluster support

- docs/CLI.md
- pkg/parser/k8s_client.go
- pkg/parser/relationship.go
- pkg/parser/relationship_test.go
- pkg/parser/relationship_types.go
Allows defining custom relationships between Kubernetes resources in a `~/.cyphernetes/relationships.yaml` file. This is useful when working with custom resources or when you want to define relationships that aren't built into Cyphernetes.
Example relationships.yaml:
```yaml
relationships:
- kindA: applications.argoproj.io
kindB: services
relationship: ARGOAPP_SYNC_SERVICE
matchCriteria:
- fieldA: "$.spec.source.targetRevision"
fieldB: "$.metadata.labels.targetRevision"
comparisonType: ExactMatch
- fieldA: "$.spec.project"
fieldB: "$.metadata.labels.project" 
comparisonType: ExactMatch
- kindA: pods
kindB: deployments
relationship: DEPLOYMENT_OWN_POD
matchCriteria:
- fieldA: "$.metadata.name"
fieldB: "$.metadata.name"
comparisonType: StringContains
```
The relationships.yaml file supports …
> Support custom relationships

- cmd/cyphernetes/shell.go
This PR addresses the issue reported on #159 where the parameter `namespace` is being ignored when the Kubernetes context is set via `kubectl config set-context`.
Tested with:
```
❯ kubectl config set-context --current --namespace=test                                                                                                                                    
Context "default" modified.
❯ ./dist/cyphernetes shell 
...
(default) test » 
❯ ./dist/cyphernetes shell --namespace default
...
(default) default » 
❯ kubectl config set-context --current --namespace=default                                                                                                                                  
Context "default" modified.
❯ ./dist/cyphernetes shell 
...
(default) default » 
❯ …
```
> fix(shell): parameter namespace is being ignored

- cmd/cyphernetes/shell.go
- pkg/core/k8s_query.go
- pkg/core/lexer.go
- pkg/core/lexer_test.go
- pkg/core/parser_test.go
- pkg/provider/apiserver/provider.go
This PR addresses the issue of ambiguity in kinds with more than 1 group.
Cyphernetes will now alert on ambiguity, show the available kinds and tell the user to choose one.
The parser and default provider now support looking resources up by fully qualified names.
> fix(parser): support fully qualified kinds

- cmd/cyphernetes/api.go
This PR addresses the issue #163 where an incorrect namespace is being displayed in the Web UI.
I have tested that:
- Web UI now shows the correct namespace
- Web UI query the right namespace
- `query` functionality works as expected
- `shell` functionality works as expected
---
Detailed tests:
```
❯ kubectl config set-context --current --namespace=test
Context "default" modified.
❯ kubectl config get-contexts
CURRENT   NAME      CLUSTER   AUTHINFO   NAMESPACE
*         default   default   default    test
❯ kubectl get deployments --namespace default
No resources found in default namespace.
❯ kubectl get deployments --namespace test
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
test2   1/1     1            1           47m
❯ ./dist/cyphernetes web
❯ curl -s …
```
> fix(web): incorrect namespace displayed in UI

- cmd/cyphernetes/query.go
- cmd/cyphernetes/query_test.go
- cmd/cyphernetes/root.go
- cmd/cyphernetes/shell.go
- pkg/core/k8s_query.go
This PR implements the feature described in #158
I added a `--format` flag as a way to choose the output format for query and shell commands. I added it as a global flag just like the `--no-color` flag.
Also, I tried to look for a library to color yaml just like it's done with the json output but couldn't find any.
> feat(cli): add format flag

- pkg/provider/apiserver/provider.go
> fix: handle non namespaced resources properly

- pkg/core/e2e/e2e_test.go
- pkg/core/k8s_query.go
- pkg/provider/apiserver/provider.go
add tests for edge cases on bad inputs.
uncovered and closed 2 bugs on nil input.
> chore: more e2e tests

- README.md
- cmd/cyphernetes/api.go
- cmd/cyphernetes/shell.go
- cmd/cyphernetes/shell_test.go
- docs/LANGUAGE.md
- go.mod
- pkg/core/e2e/e2e_test.go
- pkg/core/k8s_query.go
- pkg/core/k8s_query_test.go
- pkg/core/kind_resolution_test.go
- pkg/core/lexer_test.go
- pkg/core/parser.go
- pkg/core/parser_test.go
- pkg/core/relationship.go
- pkg/core/types.go
This PR introduces a much desired language feature, the ability to use **anonymous nodes** (nodes without a variable name such as `(:configMap)`) and **kindless nodes** (nodes without a kind label such as `(x)`) - as well as nodes that are both anonymous AND kindless, (simply `()`).
Anonymous nodes allow adding nodes in a node pattern where no data is to be returned/patched/deleted in a subsequent clause - and therefore the variable name is redundant. 
For example:
```graphql
MATCH (cm:ConfigMap)->(:Pod) RETURN cm
```
Will return all confimaps that are attached to pods, where we don't care about returning these pods later.
Under the hood, Cyphernetes will assign a variable name for the node behind the scenes. This allows for leaner queries without redundancy.
Kindless nodes allow for …
> Partial node patterns

- pkg/core/k8s_query.go
- pkg/core/kind_resolution_test.go
- pkg/core/relationship.go
Fixes 2 issues:
1. in expanded queries, where a specified kind is ambiguous, the error did not return the provider's ambiguity message with available kinds
2. expanded nodes which are in themselves ambiguous - will not be ambiguous anymore since the potential kind cache has been altered to always use full GRs.
> fix: unable to resolve ambiguity in expanded queries

- docs/LANGUAGE.md
- pkg/core/e2e/e2e_test.go
- pkg/core/k8s_query.go
- pkg/core/lexer.go
- pkg/core/lexer_test.go
- pkg/core/parser_test.go
This fixes a regression in the new parser version that incorrectly handled escaped dots in jsonPaths i.e.:
```graphql
MATCH (d:deploy)->(p:pod) WHERE d.metadata.annotations.meta\.cyphernet\.es/foo = "bar" RETURN d.metadata.annotations.meta\.cyphernet\.es/foo
```
It fixes it for both WHERE and RETURN clauses.
> Fix escape dots in jsonPaths

- pkg/core/k8s_query.go
During regular [operator e2e testing](https://github.com/AvitalTamir/cyphernetes/actions/runs/13228990928/job/36923496810) we came across a race condition while writing to the resultMap.
This PR adds missing mutex locks around this write, as well as a similar missing protection around writing to the result cache.
> Add resultMap+cache mutex protection

- pkg/core/e2e/e2e_test.go
- pkg/core/k8s_query.go
- pkg/core/parser.go
- pkg/core/parser_test.go
- pkg/core/types.go
This PR adds the ability to use patterns inside WHERE clauses which is especially useful for discovering orphaned resources.
Examples:
```graphql
MATCH (cm:ConfigMap)
WHERE NOT (cm)->(:Pod)
RETURN cm
```
```graphql
MATCH (s:Service)
WHERE NOT (s)->(:Endpoints)
RETURN s.metadata.name;
```
```graphql
MATCH (pvc:PersistentVolumeClaim)
WHERE NOT (pvc)->(:Pod)
AND pvc.status.phase = "Bound"
RETURN pvc.metadata.name;
```
Closes #198
> Graph Patterns in WHERE Clause

- cmd/cyphernetes/shell-autocomplete.go
Fix a panic in web when a query is already inputted and the cursor is moved back to beginning of line
> fix(web): prevent panic when autocompleting in beginning of line

- pkg/core/relationship.go
this makes sure we create a relationships when a field's name is "name" and it's parent resolves to a valid GVR.
example:
```
kind: pod
spec:
configmap:
name: foo
```
will create a relationship rule between pods a configmaps
> feat: add relationship when parent prop is a GVR and child prop 'name'

- pkg/provider/apiserver/provider.go
Fix for including only CRDs with `list` verb available to be added as known resource kinds. 
There are CRDs which have `create`, `delete` with no list verbs, where this logic actually breaks. Rather than check if more than one verb is present, 
```
if len(r.Verbs) > 1 {
```
a better way to check is if actual `list` verb is available in the list of verb strings.
```
if strings.Contains(fmt.Sprintf("%v", r.Verbs), "list") {
```
> Fix crd without list verb
